-- +goose Up
CREATE TABLE admin_user (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE session (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES admin_user (id) ON DELETE CASCADE,
    token_sha256 bytea NOT NULL UNIQUE,
    csrf text NOT NULL,
    flash text NOT NULL DEFAULT '',
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE node (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    role text NOT NULL CHECK (role IN ('dns', 'proxy')),
    name text NOT NULL UNIQUE,
    public_ipv4 inet,
    public_ipv6 inet,
    region text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    config_version bigint NOT NULL DEFAULT 0,
    last_seen_at timestamptz,
    token_sha256 bytea NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE domain (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL UNIQUE,
    match_kind text NOT NULL CHECK (match_kind IN ('suffix', 'fqdn')),
    enabled boolean NOT NULL DEFAULT true,
    comment text NOT NULL DEFAULT '',
    balance text NOT NULL CHECK (balance IN ('round_robin', 'weighted', 'sticky24'))
);

CREATE TABLE domain_proxy (
    domain_id uuid NOT NULL REFERENCES domain (id) ON DELETE CASCADE,
    proxy_node_id uuid NOT NULL REFERENCES node (id) ON DELETE CASCADE,
    weight integer NOT NULL CHECK (weight > 0),
    PRIMARY KEY (domain_id, proxy_node_id)
);

CREATE TABLE client_cidr (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    cidr inet NOT NULL UNIQUE,
    label text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE upstream (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    addr text NOT NULL UNIQUE,
    ordinal integer NOT NULL
);

CREATE TABLE setting (
    id integer PRIMARY KEY CHECK (id = 1),
    ttl integer NOT NULL DEFAULT 30,
    pull_interval_sec integer NOT NULL DEFAULT 5,
    retention_days integer NOT NULL DEFAULT 7,
    bootstrap_cidr text NOT NULL DEFAULT '',
    session_limit integer NOT NULL DEFAULT 64,
    dial_timeout_ms integer NOT NULL DEFAULT 5000,
    idle_timeout_ms integer NOT NULL DEFAULT 120000
);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at timestamptz NOT NULL DEFAULT now(),
    actor text NOT NULL,
    action text NOT NULL,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX audit_log_at_idx ON audit_log (at DESC);

CREATE SEQUENCE dns_hit_id_seq;

CREATE TABLE dns_hit (
    id bigint NOT NULL DEFAULT nextval('dns_hit_id_seq'),
    day date NOT NULL,
    at timestamptz NOT NULL,
    node_id uuid REFERENCES node (id) ON DELETE SET NULL,
    client_ip inet,
    qname text NOT NULL,
    qtype text NOT NULL,
    rcode text NOT NULL,
    decision text NOT NULL,
    PRIMARY KEY (day, id)
) PARTITION BY RANGE (day);

CREATE INDEX dns_hit_at_idx ON dns_hit (at DESC);
CREATE INDEX dns_hit_qname_idx ON dns_hit (qname);
CREATE INDEX dns_hit_client_idx ON dns_hit (client_ip);

CREATE SEQUENCE proxy_session_id_seq;

CREATE TABLE proxy_session (
    id bigint NOT NULL DEFAULT nextval('proxy_session_id_seq'),
    day date NOT NULL,
    at timestamptz NOT NULL,
    node_id uuid REFERENCES node (id) ON DELETE SET NULL,
    client_ip inet,
    sni text NOT NULL,
    bytes_up bigint NOT NULL DEFAULT 0,
    bytes_down bigint NOT NULL DEFAULT 0,
    status text NOT NULL,
    dial_error text NOT NULL DEFAULT '',
    PRIMARY KEY (day, id)
) PARTITION BY RANGE (day);

CREATE INDEX proxy_session_at_idx ON proxy_session (at DESC);
CREATE INDEX proxy_session_sni_idx ON proxy_session (sni);
CREATE INDEX proxy_session_client_idx ON proxy_session (client_ip);

CREATE TABLE dns_snapshot (
    version bigint PRIMARY KEY,
    body jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE proxy_snapshot (
    node_id uuid NOT NULL REFERENCES node (id) ON DELETE CASCADE,
    version bigint NOT NULL,
    body jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (node_id, version)
);

-- +goose StatementBegin
DO $$
DECLARE
    d date;
BEGIN
    FOR d IN
        SELECT generate_series((current_date - 1), (current_date + 2), interval '1 day')::date
    LOOP
        EXECUTE format(
            'CREATE TABLE dns_hit_%s PARTITION OF dns_hit FOR VALUES FROM (%L) TO (%L)',
            to_char(d, 'YYYYMMDD'), d, d + 1
        );
        EXECUTE format(
            'CREATE TABLE proxy_session_%s PARTITION OF proxy_session FOR VALUES FROM (%L) TO (%L)',
            to_char(d, 'YYYYMMDD'), d, d + 1
        );
    END LOOP;
END $$;
-- +goose StatementEnd

-- +goose Down
DROP TABLE IF EXISTS proxy_snapshot;
DROP TABLE IF EXISTS dns_snapshot;
DROP TABLE IF EXISTS proxy_session;
DROP TABLE IF EXISTS dns_hit;
DROP SEQUENCE IF EXISTS proxy_session_id_seq;
DROP SEQUENCE IF EXISTS dns_hit_id_seq;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS setting;
DROP TABLE IF EXISTS upstream;
DROP TABLE IF EXISTS client_cidr;
DROP TABLE IF EXISTS domain_proxy;
DROP TABLE IF EXISTS domain;
DROP TABLE IF EXISTS node;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS admin_user;
